[package]
name = "edh-testing-tool-client"
version = "0.1.0"
description = "Desktop client for the EDH power analysis tool"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
open = "5"

[profile.release]
lto = true
codegen-units = 1
